apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: tp-kube-3
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        ports:
        - containerPort: 80
          name: http-pma
        env:
        - name: PMA_HOST
          value: mysql-service.tp-kube-3.svc.cluster.local
        - name: PMA_PORT
          value: "3306"
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_USER
          value: test
        - name: PMA_PASSWORD
          value: test
